# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 48733bd15f533f5320211bd00b2b6a03bd4ba7cfea830ef1b9742327e38647d2ba4a8db41f3e47cc82e4fba215c4d36e08613a96c4a76c59548182196878078b

test:
  secret_key_base: a9dfe6fb686f3dc3da9aecb8aa2938c5b07cedcd1534821634817e599e73d844cfdc1607a13ddad663872a3dcc2d3e8fcfe8be2af2b3921fe3e178c9875f08e8

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
